# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 792856fa6f79e0940cd3b10989c33965574eaab5f2c06739832db269896b56b2833bf052b8fc1c02a750348c11eaaa1a667fd6d94a9b703e5021f42d9cd17fbc

test:
  secret_key_base: 55d23018e4066138ee63ed14d00423596575edcdf9135fb76a18dcfee749b758b6c611c437e45d1c89ab9af3648aba2b44196762b746f47814059f501c8f4347

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
